name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tsc:
    name: compiling
    runs-on: ubuntu-latest
    steps:
      - uses: volta-cli/action@v1
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run tsc
  build:
    name: Build MTG PlayerBoard
    runs-on: ubuntu-latest
    steps:
      - uses: volta-cli/action@v1
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build
  deploy:
    needs: [tsc, build]
    name: Deploying to hetzner server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder'
      - run: ssh-keyscan -H ${{ secrets.HETZNER_SERVER_IP }} >> ~/.ssh/known_hosts
      - run: scp -r ./build/* ${{ secrets.HETZNER_SERVER_USER }}@${{ secrets.HETZNER_SERVER_IP }}:/var/www/mtg
    